services:
#  runner:
#    build:
#      context: runner/
#      dockerfile: runner/Dockerfile
#    ports:
#      - 3001:3001
#    container_name: cloud-sml-runner
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sDTxh0i2iNR_!8kleSF
    restart: always
    ports:
      - 27017:27017
    container_name: cloud-sml-db
    volumes:
      - ./db:/data/db